import "./style/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./partials/header";
import { ThemeProvider } from "./Provider/ThemeProvider";
import SideBar from "./partials/sidebar";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader color="red" />
        <Header />
        <div className="flex">
          <SideBar />
          <main className="max-w-screen-xl mx-auto">{children}</main>
        </div>

        {/* <ThemeProvider></ThemeProvider> */}
      </body>
    </html>
  );
}
